parser: babel-eslint

extends:
  - airbnb

env:
  browser: true

# see https://eslint.org/docs/user-guide/configuring#specifying-globals
globals:
  process: false  # allow webpack `process.env[*]` variables

rules:
  # Intentional exceptions to Airbnb rules:
  no-alert: off  # currently used in the UI
  no-underscore-dangle: [error, allow: [__REDUX_DEVTOOLS_EXTENSION_COMPOSE__]]
  no-unused-vars: [error, argsIgnorePattern: "^_" ]
  react/jsx-no-target-blank: off

  # Airbnb exceptions that we should fix:
  no-console: off
  no-param-reassign: warn
  no-restricted-globals: warn
  react/no-find-dom-node: warn
  react/prop-types: off           # TODO: #123

  # TODO: #118 accessibility
  jsx-a11y/anchor-is-valid: off
  jsx-a11y/click-events-have-key-events: off
  jsx-a11y/label-has-for: off
  jsx-a11y/no-static-element-interactions: off

overrides:
  # server:
  - files: [ "server/*.js", "server.js", "sslify.js", "webpack.config.js" ]
    parser: esprima
    env:
      browser: false
      node: true
    rules:
      no-console: off
      global-require: off  # this warning doesn't apply to non-babel server
  # tests:
  - files: [ "**/__test__/**/*.js", "**/*.test.js", "**/*.test.jsx" ]
    env:
      jest: true
    rules:
      import/no-extraneous-dependencies: off
      react/jsx-indent: false
  - files: [ "actions.js" ]
    rules:
      no-use-before-define: off
  - files: [ "index.html.js" ]
    rules:
      max-len: off
