parser: babel-eslint

extends:
  - airbnb

env:
  browser: true

# see https://eslint.org/docs/user-guide/configuring#specifying-globals
globals:
  process: false  # allow webpack `process.env[*]` variables

rules:
  max-len: [warn, { code: 120 }]
  # exceptions from eslint:recommended:
  no-unused-vars: [error, { argsIgnorePattern: "^_" }]
  # exceptions from plugin:react/recommended:
  react/no-find-dom-node: warn
  react/prop-types: off           # TODO: #123

  # exceptions from airbnb style:
  camelcase: warn
  consistent-return: warn
  guard-for-in: warn
  import/no-unresolved: warn
  import/no-webpack-loader-syntax: warn
  import/prefer-default-export: warn
  jsx-a11y/anchor-is-valid: warn
  jsx-a11y/click-events-have-key-events: warn
  jsx-a11y/label-has-for: warn
  jsx-a11y/no-static-element-interactions: warn
  no-alert: warn
  no-mixed-operators: warn
  no-param-reassign: warn
  no-plusplus: warn
  no-restricted-globals: warn
  no-restricted-syntax: warn
  no-underscore-dangle: warn
  no-use-before-define: warn
  prefer-destructuring: warn
  react/forbid-prop-types: warn
  react/jsx-filename-extension: warn
  react/jsx-no-target-blank: warn
  react/no-multi-comp: warn
  react/no-unused-prop-types: warn
  react/no-unused-state: warn
  react/prefer-stateless-function: warn
  react/require-default-props: warn
  react/sort-comp: warn

  # Fixable exceptions to Airbnb style guide.
  indent: off
  react/jsx-indent: off

overrides:
  # server:
  - files: [ "index.html.js", "server.js", "webpack.config.js" ]
    parser: esprima
    env:
      browser: false
      node: true
    rules:
      no-console: off
      global-require: off  # this warning doesn't apply to non-babel server
  # tests:
  - files: [ "**/__test__/**/*.js ", "**/*\\.test\\.js" ]
    env:
      jest: true
